### ISSUE TITLE
JavaScript import into JS file

### ISSUE THREAD

**Issue by NJRBailey** [georgique/world-geojson#12]
Hello, thanks so much for your hard work on this project, it's really useful! 😄 

I am trying to use the package from NPM in a Node.js project I am working on, but currently the package is not set up to allow it to be imported into a `.js` file. It would not be difficult to allow this for both Node.js and browser usage, as JS can parse `.json` files into JavaScript objects using the `require` keyword. This code can be seen at https://github.com/georgique/world-geojson/pull/13

However, the only barrier to this is that the Canadian states use the `.geojson` file extension, which JS does not recognise and cannot import. This makes it more difficult to import.

I have some questions:
1. Is it intentional that these are `.geojson` files?
2. Are you planning on making the other `.json` files into `.geojson`?
3. Do you like the idea of allowing the files to be imported in this way?
4. If you would rather not have this feature in this project, would you be happy for me to make a separate package which allows this feature somehow?

Thank you very much for your time!

**Comment by georgique** [comment]
Hey there,

Answering your questions:
1 - not intentional, but rather accidental
2 - no, I plan to keep things being .json, especially since you say it makes life easier
3 - looks nice, will have to see final implementation. For example this line:
`geoJson.forCountry("Antigua & Barbuda"); // Converts to "antigua_and_barbuda"`
What would happen with
`geoJson.forCountry("Antigua and Barbuda");`
or
`geoJson.forCountry("Antigua And Barbuda");`
4 - I don't mind this feature to be added to the repo as long as people can still access the json files directly if needed

Thanks,
George

**Comment by NJRBailey** [comment]
Thanks very much for the quick and positive response - I will finish the code up and tag you once the PR is ready for review 🙂

**Comment by NJRBailey** [comment]
@georgique The PR is ready here https://github.com/georgique/world-geojson/pull/13 - I couldn't tag you in it directly

**Comment by georgique** [comment]
Accepted and released v3.1.0, thanks @NJRBailey
